#::= from_template_common ::#
lr: 0.0001 # learning rate
z_dim: 100 # input dimension
d_filters: 64 # number of filters in the first conv layer of discriminator
g_filters: 64 # number of filters in the first conv layer of generator
